services:
    web:
        image: hkauxy/entrymd:latest
        ports:
            - "8080:8080" # match this (both sides) with your values from env.port
        environment:
            PORT: "8080" # optional, 8080 is default
            NAME: "Entry" # optional, Entry is default
            ADMIN_PASSWORD: "supersecretpassword" # !!!CHANGE THIS!!! (required)
            DATA_LOCATION: ":cwd/data" # optional, :cwd/data is default
            USE_SINGLE_FORM_COLUMN: true # optional, makes paste information boxes display in the same column, true is default
